### ISSUE TITLE
Feature: Support for additional template words

### ISSUE THREAD

**Issue by j-xella** [kungfusheep/randomword.nvim#1]
I understand that ATM `<word>` and `<cursor>` are supported. I propose more:

 * `<file:xxx>` - to be replaced with the full name of the current file. if `:xxx` part is provided, it is treated like vim `%` expansion, for example `<file:t>` is just the current file name, without the path.  Or maybe `<%:t>` would be enough?
 * `<line>` - current line where the comment statement is inserted
 * `<git>` - the current git commit hash

**Comment by kungfusheep** [comment]
hi @j-xella - sorry, missed this issue! this is implemented by #3
